{% set name = "tramway" %}
{% set version = "0.6.4-1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DecBayComp/TRamWAy/archive/v{{ version }}.tar.gz
  sha256: b85d7c01728b16a857ce6234eadf618d1bd954774a2440c4fe2963cce13d1ec5

build:
  skip: true  # [py<36]
  number: 0
  # remove polytope as soon as the package is available in some conda channel, if it ever is
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python
  run:
    - setuptools
    - hdf5
    - python
    - rwa-python
    - matplotlib-base
    - cvxopt
    - polytope
    - tqdm
    - scikit-image
    - stopit  # [not win]

test:
  imports:
    - tramway
  source_files:
    - tests/test_core.py
    - tests/test_analyzer.py
    - tests/test_analyzer_pipeline.py
  requires:
    - pytest
  commands:
    - pytest tests/test_core.py tests/test_analyzer.py::TestSptDataAccess tests/test_analyzer.py::TestTesseller tests/test_analyzer.py::TestIndexer tests/test_analyzer.py::TestAssignment tests/test_analyzer.py::TestSideEffects

about:
  home: https://github.com/DecBayComp/TRamWAy
  license: CECILL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'The RAndom Walk AnalYzer: analysis toolbox for localization microscopy data'
  doc_url: https://tramway.readthedocs.io/

extra:
  recipe-maintainers:
    - DecBayComp
