{% set name = "tramway" %}
{% set version = "0.6.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/DecBayComp/TRamWAy/archive/v{{ version }}.tar.gz
  sha256: 4c7aed80557ffd5c060bcb2c45ba197bad5ea633e9f3fc40ca7b6e92adb527c6

build:
  skip: true  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps . -vv

requirements:
  host:
    - pip
    - python
  run:
    - setuptools
    - hdf5
    - python
    - rwa-python
    - matplotlib-base
    - cvxopt
    - polytope
    - tqdm
    - scikit-image
    - stopit  # [not win]

test:
  imports:
    - tramway
  source_files:
    - tests/test_core.py
    - tests/test_analyzer.py
    - tests/test_analyzer_pipeline.py
  requires:
    - pytest
  commands:
    - pytest tests/test_core.py tests/test_analyzer.py::TestSptDataAccess tests/test_analyzer.py::TestTesseller tests/test_analyzer.py::TestIndexer tests/test_analyzer.py::TestAssignment tests/test_analyzer.py::TestSideEffects

about:
  home: https://github.com/DecBayComp/TRamWAy
  license: CECILL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'The RAndom Walk AnalYzer: analysis toolbox for localization microscopy data'
  doc_url: https://tramway.readthedocs.io/

extra:
  recipe-maintainers:
    - DecBayComp
